### ISSUE TITLE
Defining an ellipsoid with proj4 with semi_major_axis and inverse_flattening

### ISSUE THREAD

**Issue by rogerlew** [karimbahgat/PyCRS#15]
It should be possible to define an ellipsoid with +a and +rf.
+f = 1 / +rf

`
>>> import pycrs
>>> pycrs.__version__
'0.1.3'
>>> proj4 = '+proj=lcc +lat_1=25.0 +lat_2=60.0 +lon_0=-100.0 +lat_0=42.5 '\
...         '+a=6378137.0 +rf=298.257223563 +units=m +no_defs'
>>>
>>> crs = pycrs.parser.from_unknown_text(proj4)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pycrs/parser.py", line 746, in from_unknown_text
    crs = from_proj4(text, strict)
  File "/usr/local/lib/python2.7/dist-packages/pycrs/parser.py", line 493, in from_proj4
    raise Exception("Could not find the required +ellps element, nor a manual specification of the +a or +f elements.")
Exception: Could not find the required +ellps element, nor a manual specification of the +a or +f elements.
>>>
`

Thank you

**Comment by rogerlew** [comment]
pycrs is treating +f as the inverse_flattening parameter. According to page 12 of  [this pdf](http://dl.maptools.org/dl/omsug/osgis2004/PROJ4_HandlingCoordinateSystems.pdf) +rf is the inverse_flattening parameter. [This documentation](http://proj4.org/parameters.html) also suggests +rf is the inverse (reciprocal) and that +f is the flattening parameter.

I believe that +a=6378137.0 +rf=298.257223563 should produce a WKT with
 SPHEROID["Unknown", 6378137.0, 298.257223563]

[SPHEROID documentation](http://docs.geotools.org/stable/javadocs/org/opengis/referencing/doc-files/WKT.html#SPHEROID)

**Comment by rogerlew** [comment]
Hi,
I created a pull request with a fix. In the process of implementing the fix I found that the parser is looking for +lat1 instead of +lat_1 and +lat2 instead of +lat_2.  Accroding to [this documentation](http://proj4.org/parameters.html) the parallels should have underscores.

**Comment by micahcochran** [comment]
> I created a pull request with a fix.

PR #16

**Comment by karimbahgat** [comment]
This is great, I didn't always fully understand the specs, so appreciate pointing this out. Fixed in #16.
