### ISSUE TITLE
from_epsg_code TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by mullenkamp** [karimbahgat/PyCRS#17]
Using Python 3.6, the function from_epsg_code is no longer usable. I'm guessing this also might apply to python 3.5 as well.

```python
from_epsg_code(2193)

Traceback (most recent call last):

  File "<ipython-input-1598-a3ae4c743002>", line 1, in <module>
    from_epsg_code(2193)

  File "E:\programs\anaconda3_64bit\lib\site-packages\pycrs\parser.py", line 35, in from_epsg_code
    crs = from_proj4(proj4)

  File "E:\programs\anaconda3_64bit\lib\site-packages\pycrs\parser.py", line 430, in from_proj4
    partdict = dict([part.split("=") for part in string.split()

  File "E:\programs\anaconda3_64bit\lib\site-packages\pycrs\parser.py", line 431, in <listcomp>
    if len(part.split("=")) == 2 ])

TypeError: a bytes-like object is required, not 'str'
```

Thanks.

**Comment by mullenkamp** [comment]
This can be fixed by adding .decode() to the end of the code on line 87 of utils module and function crscode_to_string.

i.e.
result = urllib2.urlopen(link).read().decode()

**Comment by karimbahgat** [comment]
Merged PR which fixes this.

**Comment by HTenkanen** [comment]
@mullenkamp @karimbahgat: I am still seeing this behavior at least on Linux Machines. Have tested installation with `pip install pycrs` and also with conda: `conda -c conda-forge pycrs`. Both of them produces the same error (tested on Python 3.5 and Python 3.6). 

On my Windows machine, I have been able to use the `from_epsg_code()` function normally. Python 3.6 with PyCRS 0.1.3.

**Comment by alessiodl** [comment]
Same errore.
Anaconda on Windows, Python 3.7, pycrs 0.1.3
