### ISSUE TITLE
Add package to conda-forge

### ISSUE THREAD

**Issue by djhoese** [karimbahgat/PyCRS#19]
https://github.com/conda-forge/staged-recipes

This would make it easier for people using conda (via the conda-forge channel) to install PyCRS.

**Comment by karimbahgat** [comment]
Will look at doing this after pushing the newest changes to pypi.

**Comment by snowman2** [comment]
In progress: https://github.com/conda-forge/staged-recipes/pull/6678.
It would be good to include the LICENSE.txt in the next release of pycrs to pypi for the conda-forge build.

@karimbahgat, I added you as a maintainer, so you can make updates once the pycrs-feedstock is created. If you would prefer not to be a maintainer, just let me know and I can update that.

**Comment by karimbahgat** [comment]
Thanks for taking care of that @snowman2. Hope to update the pypi version with the license.txt in the next week.

**Comment by snowman2** [comment]
Issue resolved: https://github.com/conda-forge/pycrs-feedstock

**Comment by karimbahgat** [comment]
That's great, thanks for the effort @snowman2 and @djhoese! So that means it's included or at least available via Anaconda then?

**Comment by snowman2** [comment]
It is and you can add this badge to the readme: 
```
[![Anaconda-Server Badge](https://anaconda.org/conda-forge/pycrs/badges/version.svg)](https://anaconda.org/conda-forge/pycrs)
```

**Comment by djhoese** [comment]
To be clear (and so this doesn't get mis-advertised) the package is available through the conda channel called `conda-forge` which many in the scientific community use. So it is not available from the default channel that comes configured for Anaconda/miniconda. The conda-forge channel has to be added to your configuration (with a single simple command).
