### ISSUE TITLE
Add continuous integration (CI) tests

### ISSUE THREAD

**Issue by djhoese** [karimbahgat/PyCRS#20]
It would be nice to see this project get CI integration with travis (linux and OSX) and appveyor (Windows) to prove that the tests pass now and when changes are made in the future.

I find it useful to use astropy's ci-helpers repository/utility: https://github.com/astropy/ci-helpers

I can provide some information if this is something you'd be interested in.

**Comment by karimbahgat** [comment]
Added extensive examples to the readme, and continuous testing of these using Travis CI for both Py2 and 3. Thanks for getting this started - much needed!
