### ISSUE TITLE
Accept proj4 as dict?

### ISSUE THREAD

**Issue by karimbahgat** [karimbahgat/PyCRS#23]
Some libraries create proj4 representations as dicts instead of as a string. Probably useful to accept such a proj4 dict. This would be easy since internally we transform the string to dict anyway. 

Should this be in a separate method `loader.from_proj4_dict`, or just allow `loader.from_proj4()` to accept either string or dict? @djhoese?

**Comment by micahcochran** [comment]
> just allow `loader.from_proj4()` to accept either string or dict?

I'd prefer to just allow `from_proj4()` to accept either.  Within that function it is already converting the proj4 string into a dictionary.  One function that accepts either seem more pythonic to me.  My 2 cents.

**Comment by karimbahgat** [comment]
Sounds good, that would be my preference too, simpler API and more flexible input. And agree about `+` key signs.

**Comment by karimbahgat** [comment]
Added in 8f8857c302aa52cb0969976e61f73f1b0e588634.
