### ISSUE TITLE
Broken `from_unknown_text` method

### ISSUE THREAD

**Issue by rtodea** [karimbahgat/PyCRS#6]
Method `from_unknown_text` is not working.

I guess this is due to some refactoring.
The local variable `string` is not present in the [method signature](https://github.com/karimbahgat/PyCRS/blob/master/pycrs/parser.py#L726).

Steps to reproduce
------
```
from pycrs.parser import from_unknown_text
from_unknown_text('some_dummy_text')
```
Actual
-----
```
NameError: global name 'string' is not defined
```
Expected
----
```
Exception: Could not detect which type of crs
```

**Comment by micahcochran** [comment]
@rtodea Please check out my PR #4. It should fix that function.

**Comment by rtodea** [comment]
@micahcochran, it does fix the issue.
Please close this issue after the PR is merged into master.

**Comment by karimbahgat** [comment]
Merged.
