### ISSUE TITLE
+units on proj.4 representation

### ISSUE THREAD

**Issue by micahcochran** [karimbahgat/PyCRS#8]
When using units that are not meters causes problems for pyproj with proj.4 representations.

I am using ESRI:102630 which uses US Survey Feet as its units which is 0.3048006096 m.  (It is different from "International feet" or "Feet" which is 0.3048 m.)

```Python
In [19]: import pycrs

In [20]: official = pyproj.Proj('+proj=tmerc +lat_0=30 +lon_0=-87.5 +k=0.9999333
333333333 +x_0=600000.0000000001 +y_0=0 +ellps=GRS80 +datum=NAD83 +to_meter=0.30
48006096012192 +no_defs', preserve_units=True)

In [21]: alw_esri = pycrs.parser.from_esri_code(102630)

In [25]: alw_esri.to_proj4()
Out[25]: '+proj=tmerc +datum=NAD83 +ellps=GRS80 +a=6378137.0 +f=298.257222101 +p
m=0  +lon_0=-87.5 +x_0=600000.0000000001 +y_0=0 +k_0=0.9999333333333333 +lat_0=3
0 +units=m +to_meter=0.3048006096012192 +axis=enu +no_defs'

In [22]: converted = pyproj.Proj(alw_esri.to_proj4(), preserve_units=True)

# expected output
In [23]: official(-87.0, 34.75)
Out[23]: (2118695.32804112, 1728420.6727422967)

In [24]: converted(-87.0, 34.75)
Out[24]: (645779.6275461884, 526823.6746992014)  # give meter units
```

Note the return string for`alw_esri.to_proj4()` contains `+units=m +to_meter=0.3048006096012192`.  It seems like there should not be a `+unit` and `+to_meter` in the same proj.4 code (see [Proj.4's Wiki GenParms Units](https://github.com/OSGeo/proj.4/wiki/GenParms#units).  I've also seen US survey feet represented as `+units=us-ft` in proj.4 projection codes.  

I've worked on this problem a little, but I don't think I quite understand the code enough to make that design decision.  The WKT representations seem to depend on the unit and conversion to meters factor being present.

**Comment by karimbahgat** [comment]
Nicely spotted. Fixed it now in most recent commit:

https://github.com/karimbahgat/PyCRS/commit/f7378f8cc012814815f998fcd5bba9d78e119250

As you say, seems like pyproj and the proj4 description that you linked to prioritizes the +units parameter, and that the +to_meter param is only considered if the +units is missing. In the newest commit therefore, to_proj4() will only output one of them, preferably +units. In addition, there was a bug with the parser and I hadn't specified the proj4 codes for us feet or international feet, which are also now fixed. Added to your contributed unittest a check on this. 

In terms of the design of the library, feel free to ask me for specifics, or if you think it should be added to the docs for contributors, but as a short answer, a crs_obj is essentially an object-oriented implementation of the WKT format nested within each other, with the various entities defined in the "elements" folder.

**Comment by micahcochran** [comment]
Thank you!
